### ISSUE TITLE
problem installation pallet

### ISSUE THREAD

**Issue by hellresistor** [easybotics/node-red-contrib-easybotics-air-quality#10]
Getting this when try install this pallet on HA-NodeRedAddon(8.1.0 ) NodeRed(v1.2.9)

```
2021-02-06T14:11:12.860Z Install : node-red-contrib-easybotics-air-quality 0.6.9

2021-02-06T14:11:12.005Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-easybotics-air-quality@0.6.9
2021-02-06T14:11:15.562Z [out] 
2021-02-06T14:11:15.562Z [out] > epoll@2.0.10 install /config/node-red/node_modules/epoll
2021-02-06T14:11:15.562Z [out] > node-gyp rebuild
2021-02-06T14:11:15.562Z [out] 
2021-02-06T14:11:16.042Z [err] gyp
2021-02-06T14:11:16.042Z [err]  ERR! build error 
2021-02-06T14:11:16.043Z [err] gyp ERR! stack Error: not found: make
2021-02-06T14:11:16.043Z [err] gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2021-02-06T14:11:16.043Z [err] gyp ERR! 
2021-02-06T14:11:16.043Z [err] stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2021-02-06T14:11:16.043Z [err] gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2021-02-06T14:11:16.043Z [err] gyp
2021-02-06T14:11:16.043Z [err]  ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2021-02-06T14:11:16.043Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2021-02-06T14:11:16.043Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2021-02-06T14:11:16.043Z [err] gyp ERR!
2021-02-06T14:11:16.043Z [err]  stack     at FSReqCallback.oncomplete (fs.js:183:21)
2021-02-06T14:11:16.043Z [err] gyp ERR! System Linux 5.4.86
2021-02-06T14:11:16.043Z [err] gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2021-02-06T14:11:16.043Z [err] gyp ERR! cwd /config/node-red/node_modules/epoll
2021-02-06T14:11:16.043Z [err] gyp ERR! node -v v14.15.4
2021-02-06T14:11:16.043Z [err] gyp ERR!
2021-02-06T14:11:16.043Z [err]  node-gyp -v v5.1.0
2021-02-06T14:11:16.043Z [err] gyp ERR! not ok 
2021-02-06T14:11:16.146Z [err] npm
2021-02-06T14:11:16.146Z [err]  
2021-02-06T14:11:16.146Z [err] ERR!
2021-02-06T14:11:16.146Z [err]  
2021-02-06T14:11:16.146Z [err] code
2021-02-06T14:11:16.146Z [err]  ELIFECYCLE
2021-02-06T14:11:16.146Z [err] npm
2021-02-06T14:11:16.146Z [err]  
2021-02-06T14:11:16.147Z [err] ERR!
2021-02-06T14:11:16.147Z [err]  
2021-02-06T14:11:16.147Z [err] errno
2021-02-06T14:11:16.147Z [err]  1
2021-02-06T14:11:16.150Z [err] npm
2021-02-06T14:11:16.150Z [err]  
2021-02-06T14:11:16.150Z [err] ERR!
2021-02-06T14:11:16.150Z [err]  epoll@2.0.10 install: `node-gyp rebuild`
2021-02-06T14:11:16.150Z [err] npm
2021-02-06T14:11:16.150Z [err]  
2021-02-06T14:11:16.151Z [err] ERR!
2021-02-06T14:11:16.151Z [err]  Exit status 1
2021-02-06T14:11:16.151Z [err] npm
2021-02-06T14:11:16.151Z [err]  
2021-02-06T14:11:16.151Z [err] ERR!
2021-02-06T14:11:16.151Z [err]  
2021-02-06T14:11:16.151Z [err] npm
2021-02-06T14:11:16.151Z [err]  
2021-02-06T14:11:16.151Z [err] ERR!
2021-02-06T14:11:16.151Z [err]  Failed at the epoll@2.0.10 install script.
2021-02-06T14:11:16.151Z [err] npm
2021-02-06T14:11:16.151Z [err]  
2021-02-06T14:11:16.151Z [err] ERR!
2021-02-06T14:11:16.151Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
2021-02-06T14:11:16.155Z [err] 
2021-02-06T14:11:16.155Z [err] npm
2021-02-06T14:11:16.155Z [err]  
2021-02-06T14:11:16.155Z [err] ERR!
2021-02-06T14:11:16.155Z [err]  A complete log of this run can be found in:
2021-02-06T14:11:16.155Z [err] npm
2021-02-06T14:11:16.155Z [err]  
2021-02-06T14:11:16.156Z [err] ERR!
2021-02-06T14:11:16.156Z [err]      /root/.npm/_logs/2021-02-06T14_11_16_153Z-debug.log
2021-02-06T14:11:16.163Z rc=1
```

**Comment by ryanmich251** [comment]
Do you have make installed on your system? It looks like npm needs it to build some dependency but can't find it.

**Comment by hellresistor** [comment]
seems resolved!
